var main_trials = [
	{
	title: 'bartlett',
	text: 'One night two young men from Egulac went down to the river to hunt seals, and while they were there it became foggy and calm. Then they heard war-cries, and they thought: "Maybe this is a war-party". They escaped to the shore, and hid behind a log. Now canoes came up, and they heard the noise of paddles, and saw one canoe coming up to the them. There were five men in the canoe, and they said: "What do you think? We wish to take you along. We are going up the river to make war on the people". One of the young men said: "I have no arrows". "Arrows are in the canoe", they said. "I will not go along. I might be killed. My relatives do not know where I have gone. But you", he said, turning to the other, "may go with them." So one of the young men went, but the other returned home. And the warriors went on up the river to a town on the other side of Kalama. The people came down to the water, and they began to fight, and many were killed. But presently the young man heard one of the warriors say: "Quick, let us go home: that Indian has been hit". Now he thought: "Oh, they are ghosts". He did not feel sick, but they said he had been shot. So the canoes went back to Egulac, and the young man went ashore to his house, and made a fire. And he told everybody and said: "Behold I accompanied the ghosts, and we went to fight. Many of our fellows were killed, and many of those who attacked us were killed. They said I was hit, and I did not feel sick". He told it all, and then he became quiet. When the sun rose he fell down. Something black came out of his mouth. His face became contorted. The people jumped up and cried. He was dead.'
	},
	{
	title: 'mesoudi_whiten',
	text: 'John and Nancy entered the restaurant and were shown to a table by the waitress. They sat down on the chairs and placed napkins on their laps. Then they looked at the menu and decided what food to have. They signalled to the waitress and told her their order, which the waitress wrote down. John and Nancy drank wine and talked until their food arrived. They ate the main course, then they had dessert. John asked for the bill, and the waitress brought it over. John took out his wallet and left money, as well as a tip. Then they both stood up and went to the cloakroom to fetch their coats. John and Nancy put on their coats and walked outside.'
	}
];